/*
  sketch.ino  (MCU side - STM32 on the Arduino UNO Q)
  -----------------------------------------------------
  Exposes non-blocking plotter functions over the Bridge so the
  Python side (main.py, running on the Linux MPU) can drive the
  X/Y steppers + pen servo on the CNC Shield.

  Servo jitter fix: the UNO Q's App Lab core is ArduinoCore-Zephyr, not
  STM32duino, so there's no HardwareTimer class here, and bit-banging
  pulses from loop() is unreliable because loop() timing is affected by
  Zephyr's scheduler, Bridge RPC calls, and stepper stepping. Arduino_
  HardwareServo drives the pin with real hardware PWM instead, so pulse
  width is generated by the timer peripheral itself and is immune to
  whatever else loop() is doing.

  Library dependencies (install via App Lab's "Add sketch library"):
    Arduino_RouterBridge    (Bridge/Monitor)
    AccelStepper
    Arduino_HardwareServo   (hardware-PWM servo driver for Zephyr boards)
*/

#include "Arduino_RouterBridge.h"
#include <AccelStepper.h>
#include <Arduino_HardwareServo.h>

// ================= CONFIGURE FOR YOUR HARDWARE =================
#define X_STEP_PIN 2
#define X_DIR_PIN  5
#define Y_STEP_PIN 3
#define Y_DIR_PIN  6
#define ENABLE_PIN 8      // LOW = drivers enabled on CNC Shield V3
#define SERVO_PIN  9        // pen servo
#define CLEANER_SERVO_PIN 11  // cleaning-cloth arm servo

// Steps per millimeter of pen travel - TUNE to your belt/pulley or
// leadscrew pitch and the driver microstepping jumpers on the shield.
float stepsPerMM_X = 80.0;
float stepsPerMM_Y = 80.0;

int penUpAngle   = 200;
int penDownAngle = 0;

int cleanerUpAngle   = 30;  // idle - cloth lifted clear of the board
int cleanerDownAngle = 0;   // engaged - cloth pressed against the board

// Pulse-width range (microseconds) corresponding to 0-180 degrees.
// 1000-2000 is a safe default for most hobby servos (e.g. SG90).
const int SERVO_PULSE_MIN_US = 1000;
const int SERVO_PULSE_MAX_US = 2000;
// ==================================================================

AccelStepper stepperX(AccelStepper::DRIVER, X_STEP_PIN, X_DIR_PIN);
AccelStepper stepperY(AccelStepper::DRIVER, Y_STEP_PIN, Y_DIR_PIN);

float curX = 0, curY = 0; // last commanded position, mm

// ---- Hardware-PWM servos (replaces the old bit-banged ServoChannel) ----
HardwareServo penServo;
HardwareServo cleanerServo;

void servoWriteAngle(HardwareServo &servo, int angleDeg) {
  angleDeg = constrain(angleDeg, 0, 180);
  int us = map(angleDeg, 0, 180, SERVO_PULSE_MIN_US, SERVO_PULSE_MAX_US);
  servo.writeMicroseconds(us);
}

// ---- Bridge-exposed functions: must return quickly, never block ----

const char* move_to(float x, float y, float feedMMperMin) {
  float dx = x - curX;
  float dy = y - curY;
  float dist = sqrt(dx * dx + dy * dy);

  if (dist > 0.0001f && feedMMperMin > 0) {
    float mmPerSec = feedMMperMin / 60.0f;
    float moveTimeSec = dist / mmPerSec;
    float xSpeed = (fabs(dx) * stepsPerMM_X) / moveTimeSec;
    float ySpeed = (fabs(dy) * stepsPerMM_Y) / moveTimeSec;
    xSpeed = max(xSpeed, 1.0f);
    ySpeed = max(ySpeed, 1.0f);
    stepperX.setMaxSpeed(xSpeed);
    stepperY.setMaxSpeed(ySpeed);
    stepperX.setAcceleration(xSpeed * 4);
    stepperY.setAcceleration(ySpeed * 4);
  }

  stepperX.moveTo((long)(x * stepsPerMM_X));
  stepperY.moveTo((long)(y * stepsPerMM_Y));

  curX = x;
  curY = y;
  return "OK";
}

int is_moving() {
  return (stepperX.distanceToGo() != 0 || stepperY.distanceToGo() != 0) ? 1 : 0;
}

const char* pen_down() {
  servoWriteAngle(penServo, penDownAngle);
  return "OK";
}

const char* pen_up() {
  servoWriteAngle(penServo, penUpAngle);
  return "OK";
}

const char* cleaner_down() {
  servoWriteAngle(cleanerServo, cleanerDownAngle);
  return "OK";
}

const char* cleaner_up() {
  servoWriteAngle(cleanerServo, cleanerUpAngle);
  return "OK";
}

void setup() {
  Bridge.begin();
  Monitor.begin();

  pinMode(ENABLE_PIN, OUTPUT);
  digitalWrite(ENABLE_PIN, LOW); // enable drivers

  stepperX.setMaxSpeed(8000);
  stepperY.setMaxSpeed(8000);
  stepperX.setAcceleration(8000);
  stepperY.setAcceleration(8000);

  penServo.attach(SERVO_PIN);
  cleanerServo.attach(CLEANER_SERVO_PIN);
  servoWriteAngle(penServo, penUpAngle);
  servoWriteAngle(cleanerServo, cleanerUpAngle);

  Bridge.provide_safe("move_to", move_to);
  Bridge.provide_safe("is_moving", is_moving);
  Bridge.provide_safe("pen_down", pen_down);
  Bridge.provide_safe("pen_up", pen_up);
  Bridge.provide_safe("cleaner_down", cleaner_down);
  Bridge.provide_safe("cleaner_up", cleaner_up);

  Monitor.println("Plotter bridge ready");
}

void loop() {
  // Non-blocking single-step polling - keep this loop as tight as possible
  stepperX.run();
  stepperY.run();
  // Servo pulses are now generated by hardware PWM via Arduino_HardwareServo,
  // no polling needed here.
}